version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: Minecraft_Summer_Edition_2025
    restart: unless-stopped
    environment:
      - TYPE=NEOFORGE
      - VERSION=1.21.4
      - NEOFORGE_VERSION=21.4.141
      - EULA=true
      - MEMORY=8G
      - ENABLE_RCON=true
      - RCON_PORT=25575
      - RCON_PASSWORD=Poule
    ports:
      - "3141:25565"
      - "1431:25575"
      - "8100:8100"      # port BlueMap pour la carte web
    volumes:
      - /home/pouletdecanon/Minecraft_Summer_Edition_2025:/data
      - /home/pouletdecanon/Minecraft_Summer_Edition_2025/start.sh:/start.sh
    entrypoint: ["/bin/bash", "/start.sh"]